import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ProvidersWrapper from './ProvidersWrapper'
import Nav from './components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ProvidersWrapper>
        <body className={inter.className}>
          <Nav />
          <main>
            {children}
          </main>
        </body>
      </ProvidersWrapper>
    </html>
  )
}
